/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as UrlRouteImport } from './routes/$url'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as PagesAddUrlRouteImport } from './routes/pages/add.$url'
import { Route as ActionBuyIdRouteImport } from './routes/action/buy/$id'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlRoute = UrlRouteImport.update({
  id: '/$url',
  path: '/$url',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAddUrlRoute = PagesAddUrlRouteImport.update({
  id: '/pages/add/$url',
  path: '/pages/add/$url',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionBuyIdRoute = ActionBuyIdRouteImport.update({
  id: '/action/buy/$id',
  path: '/action/buy/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$url': typeof UrlRoute
  '/mcp': typeof McpRoute
  '/pages/': typeof PagesIndexRoute
  '/action/buy/$id': typeof ActionBuyIdRoute
  '/pages/add/$url': typeof PagesAddUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$url': typeof UrlRoute
  '/mcp': typeof McpRoute
  '/pages': typeof PagesIndexRoute
  '/action/buy/$id': typeof ActionBuyIdRoute
  '/pages/add/$url': typeof PagesAddUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$url': typeof UrlRoute
  '/mcp': typeof McpRoute
  '/pages/': typeof PagesIndexRoute
  '/action/buy/$id': typeof ActionBuyIdRoute
  '/pages/add/$url': typeof PagesAddUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$url'
    | '/mcp'
    | '/pages/'
    | '/action/buy/$id'
    | '/pages/add/$url'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$url' | '/mcp' | '/pages' | '/action/buy/$id' | '/pages/add/$url'
  id:
    | '__root__'
    | '/'
    | '/$url'
    | '/mcp'
    | '/pages/'
    | '/action/buy/$id'
    | '/pages/add/$url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UrlRoute: typeof UrlRoute
  McpRoute: typeof McpRoute
  PagesIndexRoute: typeof PagesIndexRoute
  ActionBuyIdRoute: typeof ActionBuyIdRoute
  PagesAddUrlRoute: typeof PagesAddUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$url': {
      id: '/$url'
      path: '/$url'
      fullPath: '/$url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/add/$url': {
      id: '/pages/add/$url'
      path: '/pages/add/$url'
      fullPath: '/pages/add/$url'
      preLoaderRoute: typeof PagesAddUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action/buy/$id': {
      id: '/action/buy/$id'
      path: '/action/buy/$id'
      fullPath: '/action/buy/$id'
      preLoaderRoute: typeof ActionBuyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UrlRoute: UrlRoute,
  McpRoute: McpRoute,
  PagesIndexRoute: PagesIndexRoute,
  ActionBuyIdRoute: ActionBuyIdRoute,
  PagesAddUrlRoute: PagesAddUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
